### ISSUE TITLE
Update android target

### ISSUE THREAD

**Issue by ztefanie** [digitalfabrik/accessibility-launcher#22]
We need to update the android app target, because of google play requirements:

We won't be able to release app updates until this is done

App must target Android 14 (API level 34) or higher

To provide users with a safe and secure experience, Google Play requires all apps to meet target API level requirements.
From 31 Aug 2024, if your target API level is not within one year of the latest Android release, you won't be able to update your app.

**Comment by 8bitPit** [comment]
Thanks for the info, @ztefanie. The target SDK should already be at 35 (https://github.com/digitalfabrik/accessibility-launcher/commit/f00a5a8f210980970ea2d9d5b58a95eefd31b13e for reference), but I believe the latest version on Google Play still has the old version. Could you roll out a new update on Google Play to fix the issue? I'm afraid I don't have the necessary permissions to do that myself.

**Comment by ztefanie** [comment]
Sure can do.

Would you like to have the permissions to do this? Would be easy to give them to you as you only need access to our circleci, let me know if i should add you.

**Comment by ztefanie** [comment]
promoted version 0.3 from 03.09.2024 to production

**Comment by 8bitPit** [comment]
Thanks! As far as I know, there aren’t any new features planned at the moment, but I’ll reach out the next time something comes up.

**Comment by ztefanie** [comment]
Close as already done.

**Comment by ztefanie** [comment]
google still shows this error. But the PR you mentioned was merged before the last release :thinking: 

Google message: We will soon take action because your app does not adhere to Google Play Developer Programme Policies. Fix violations as soon as possible. App must target Android 14 (API level 34) or higher

**Comment by ztefanie** [comment]
ah ok, sorry my bad, it was an old version in the internal testing track that caused this error.
